### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by stevetoro** [amtabug/TeaCozy#2]
https://github.com/amtabug/TeaCozy/blob/master/index.html#L13-L22

Nice job using `header`, `nav`, and `footer` here to make your markup more semantic. 👍 

Try to go the extra mile and add more semantic elements, like: `main`, `section`, `menu`, `figure`, etc. These can all make your markup a lot easier to read and reason about.

**Comment by amtabug** [comment]
I didn't know them, thanks. I will use them next time.
