### ISSUE TITLE
`img alt`

### ISSUE THREAD

**Issue by stevetoro** [amtabug/TeaCozy#4]
https://github.com/amtabug/TeaCozy/blob/master/index.html#L36-L52

Nice job giving _all_ of your `img` tags an `alt` attribute, just in case your website is not able to load it.  Try to use a value that more adequately describes the image, instead of just using "Tea" for every `img` tag. 👍 

Doing so will help improve the accessibility of your website, which might be accessed by visually impaired users on e-readers or other devices that might deliberately neglect images-- as well as any other time that your website is just unable to render images.

**Comment by amtabug** [comment]
Ok.
