### ISSUE TITLE
Classes and IDs

### ISSUE THREAD

**Issue by stevetoro** [amtabug/TeaCozy#5]
https://github.com/amtabug/TeaCozy/blob/master/index.html#L60-L77

Nice job using simple classes like `teaSelection` and `tea` in your tea section. 👍 

Try to do the same for the locations section. Use `location` instead of `subLocation`. Try to avoid truncated class names like `flexLoca`, `mainC`, or `locationsL`. Don't make another programmer guess what your classes mean.

Keep your classes simple. This will make it easier to understand your code's purpose and also to write descriptive CSS selectors.

**Comment by amtabug** [comment]
Ok.
